### PR TITLE
Make Font never outlive its RWops anymore

### LINKED ISSUE #29: Crash related to lifetime problem when creating Font from RWops.
As far as I understand RWops must outlive Font, since C library uses them after font is created.

In previous version I've just kept RWops around and bug wasn't triggered. In 0.14 method Sdl2TtfContext::load_font_from_rwops() consumes RWops, so they are dropped before the function returns and program crashes without traceback.

It's possible to add a lifetime to Font so it won't outlive RWops.

Another option is to use SDL's internal lifetime management: if second arg in ffi::TTF_OpenFontRW() is 1, then C library takes ownership of RWops and releases them when it's done. In this case rust shouldn't drop RWops since ownership is transferred to C. It's possible to just std::mem::forget(rwops) (and it works), but I think it's not a good idea. It would be better to add RWops::into_raw(self) -> ll::SDL_RWops in rust-sdl2.

What do you think?

Edit: it looks like RWops have internal state, at least current position. ~~It means that RWops shouldn't be shared between different fonts (docs are not clear on this). So rwops should be either mutably borrowed or ownership fully transferred.~~

### LINKED ISSUE #43: Reading a font from RWops makes rendering it with .solid() segfault
On Linux Debian 8, using Rust stable and latest sdl2_everything

``` .rust
extern crate sdl2;
extern crate sdl2_ttf;

use sdl2::pixels::Color;
use sdl2::rwops;

use std::path::Path;
use std::io::Read;
use std::fs::File;


pub fn make_text() -> sdl2::render::Texture {
    let sdl_context = sdl2::init().unwrap();
    let ttf_context = sdl2_ttf::init().unwrap();
    let video = sdl_context.video().unwrap();
    let window = video.window("kerblammo", 800, 600)
                               .position_centered()
                               .opengl()
                               .build().unwrap();

    let renderer = window.renderer()
        .accelerated()
        .build().unwrap();

    // Load font
    let path = Path::new("DejaVuSerif.ttf");
    let size = 24;
    let mut buffer: Vec<u8> = Vec::new();
    let mut file = File::open(path).unwrap();
    let _ = file.read_to_end(&mut buffer).unwrap();
    let rwops = rwops::RWops::from_bytes(&buffer).unwrap();

    let ttf_font = ttf_context.load_font_from_rwops(rwops, size).unwrap();
    // Works fine when I create the font with this instead
    //let ttf_font = ttf_context.load_font(path, 24).unwrap();

    let surf = ttf_font.render("Hello world")
        // If I change .solid() to .blended() it works fine.
        .solid(Color::RGB(255,255,255))
        .unwrap();
    // SEGFAULTS on create_texture_from_surface
    //  But only when using .solid() to make the surface,
    // not .blended()!
    // Does it have anything to do with the font lifetime thing???
    // It shouldn't, 'cause we still have the buffer we read into here!
    let texture = renderer.create_texture_from_surface(surf).unwrap();
    texture

}


pub fn main() {
    println!("Loading");
    let t = make_text();
    println!("Got texture");
}
```

Crashes with the message:

> error: Process didn't exit successfully: `/home/...` (signal: 11, SIGSEGV: invalid memory reference)

### PR DESCRIPTION
**Pull request by Cobrand**
* Closes #43
* Closes #29

The example linked works as usual, but I'd like to know if this fix fixes the various segfaults that happened because of it.

cc @icefoxen for testing, since you had a 100% sure way to test that.

This change breaks the API, so a version bump will be needed.

### CODE REVIEW

**Comment by icefoxen** [comment]
Sure, I'll try it out when I get a minute.

**Comment by icefoxen** [comment]
Of course, this time when I try to trigger the crash deliberately, it magically doesn't work.  Though I've managed to gin up an example that at least makes a font break by nuking the rwops's backing memory even after it's out of scope.

**Comment by andelf** [comment]
@icefoxen  wait for your good news :)

**Comment by icefoxen** [comment]
Appears to work.  The borrow checker no longer allows me to create a font from an RWops and then destroy the RWops while still having the font around.

It makes `RWops::from_bytes()` even more of a pain to use because there's no good way to create both it and a buffer for it in the same context, but that's a separate problem.

Test code:
```.rust
extern crate sdl2;
extern crate sdl2_ttf;
extern crate rand;

use sdl2::pixels::Color;
use sdl2::rwops;

use std::path::Path;
use std::io::Read;
use std::fs::File;

pub fn get_font<'a>(ttf_context: &'a mut sdl2_ttf::Sdl2TtfContext,
                    buffer: &'a mut Vec<u8>)
                    -> sdl2_ttf::Font<'a> {
    // Load font
    let path = Path::new("DejaVuSans.ttf");
    let size = 24;

    let mut file = File::open(path).unwrap();
    let _ = file.read_to_end(buffer).unwrap();
    let rwops = rwops::RWops::from_bytes(buffer).unwrap();
    let ttf_font = ttf_context.load_font_from_rwops(rwops, size).unwrap();
    ttf_font
}

pub fn make_text() -> sdl2::render::Texture {
    let sdl_context = sdl2::init().unwrap();
    let ttf_context = &mut sdl2_ttf::init().unwrap();
    let video = sdl_context.video().unwrap();
    let window = video.window("kerblammo", 800, 600)
                      .position_centered()
                      .opengl()
                      .build()
                      .unwrap();

    let renderer = window.renderer()
                         .accelerated()
                         .build()
                         .unwrap();

    let mut buffer: Vec<u8> = Vec::new();
    let ttf_font = get_font(ttf_context, &mut buffer);
    let surf = ttf_font.render("Hello world")
                       .solid(Color::RGB(255, 255, 255))
                       .unwrap();
    let texture = renderer.create_texture_from_surface(surf).unwrap();
    texture

}


pub fn main() {
    println!("Loading");
    let _ = make_text();
    println!("Got texture");
}
```

Previously, this broken `get_font()` function was permitted:
```.rust
pub fn get_font(ttf_context: &mut sdl2_ttf::Sdl2TtfContext) -> sdl2_ttf::Font {
    let path = Path::new("DejaVuSans.ttf");
    let size = 24;

    let mut buffer: Vec<u8> = Vec::new();
    let ttf_font = {
        let mut file = File::open(path).unwrap();
        let _ = file.read_to_end(&mut buffer).unwrap();
        let rwops = &mut rwops::RWops::from_bytes(&buffer).unwrap();
        ttf_context.load_font_from_rwops(rwops, size).unwrap()
    };
    for i in 0..buffer.len() {
        buffer[i] = rand::random();
    }
    ttf_font
}
```

Or even this version, which makes sure the file buffer is dropped right after the Font is created, which will segfault eventually even if it's hard to force it to:

```.rust
pub fn get_font(ttf_context: &mut sdl2_ttf::Sdl2TtfContext) -> sdl2_ttf::Font {
    let path = Path::new("DejaVuSans.ttf");
    let size = 24;

    let ttf_font = {
        let mut buffer: Vec<u8> = Vec::new();
        let mut file = File::open(path).unwrap();
        let _ = file.read_to_end(&mut buffer).unwrap();
        let rwops = &mut rwops::RWops::from_bytes(&buffer).unwrap();
        ttf_context.load_font_from_rwops(rwops, size).unwrap()
    };
    ttf_font
}
```

**Pull request merged**
