### PR TITLE
Fix building issues with rust 1.6

### PR DESCRIPTION
**Pull request by NotKild**
Fix building issues with rust 1.6.

### CODE REVIEW

**Comment by petevine** [comment]
The saboteur tries this crap again!

**Comment by NotKild** [comment]
Yup! But it doesn't build because of the rand package that's weird

**Comment by petevine** [comment]
That's completely unrelated and due to changes in nightly rust 1.7.

**Comment by NotKild** [comment]
Oh ok so how to fix this?

**Comment by petevine** [comment]
You should open an issue with `rand` if they don't already know about this.

**Comment by NotKild** [comment]
Ok but is my fix "good"? Because I need some advice

**Comment by petevine** [comment]
It should work - did you test it by running the binary?

**Comment by NotKild** [comment]
Yes it works

**Comment by petevine** [comment]
Ok then, it's probably safe to merge.

**Comment by NotKild** [comment]
Ok thanks

**Comment by petevine** [comment]
Oh, you don't have to report it anywhere - it's a known regression in nightly just as I'd suspected.

https://github.com/rust-lang/rust/issues/30713

**Comment by NotKild** [comment]
oh ok i didn't notice that

**Pull request closed without merging**
